Flownative:
  Neos:
    CustomDocumentUriRouting:
      mixinNodeTypeName: 'Flownative.Neos.CustomDocumentUriRouting:UriPathMixin'
      uriPathPropertyName: 'uriPath'
      matchExcludePatterns:
        - '_Resources'

Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            'redirectToFullNodeUri':
              position: 'after Routing'
              component: 'Flownative\Neos\CustomDocumentUriRouting\Routing\RedirectToFullNodeUrlComponent'
